theme: jekyll-theme-chirpy
lang: en
timezone: America/Detroit
title: Steven Crothers
tagline: Smoke meat, build Kubernetes.
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.
url: "https://scrothers.com"
github:
  username: scrothers
twitter:
  username: scrothers89 
social:
  name: Steven Crothers
  email: github@scrothers.com
  links:
    - https://twitter.com/scrothers89
    - https://github.com/scrothers
mode: dark
avatar: /assets/img/avatar.png
toc: true
comments:
  provider: giscus
  giscus:
    repo: scrothers/scrothers.github.io
    repo_id: MDEwOlJlcG9zaXRvcnkxMjcxODEzMw==
    category: Announcements
    category_id: DIC_kwDOAMIQNc4CgENl
    mapping: pathname
    strict: 0
    input_position: bottom
    lang: en
    reactions_enabled: 1
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA
paginate: 10
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json
  - .github/workflows/*.yml
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
